### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by Genius398** [Sreehari521/Face-and-Smile-Detector#1]
Wow you really do alot of python. Can you help with Python tutorials? @somePythonProgrammer is also helping

**Comment by N3RDIUM** [comment]
Sure, I'll help, @Genius398

**Comment by Genius398** [comment]
:-)

**Comment by Sreehari521** [comment]
> Wow you really do alot of python. Can you help with Python tutorials? @somePythonProgrammer is also helping

Oh Yeah, I will help u

**Comment by Genius398** [comment]
> > Wow you really do alot of python. Can you help with Python tutorials? @somePythonProgrammer is also helping
> 
> Oh Yeah, I will help u

thanks :)
